import type { RouteDefinition } from './astro-adapter';

export const standaloneApiRoutes: RouteDefinition[] = [
  { path: '/api/health', loadModule: () => import('../src/pages/api/health') },
  { path: '/api/test', loadModule: () => import('../src/pages/api/test') },
  { path: '/api/auth/login', loadModule: () => import('../src/pages/api/auth/login') },
  { path: '/api/auth/logout', loadModule: () => import('../src/pages/api/auth/logout') },
  { path: '/api/auth/me', loadModule: () => import('../src/pages/api/auth/me') },
  { path: '/api/auth/register', loadModule: () => import('../src/pages/api/auth/register') },
  { path: '/api/auth/verify-email', loadModule: () => import('../src/pages/api/auth/verify-email') },
  { path: '/api/auth/resend-verification', loadModule: () => import('../src/pages/api/auth/resend-verification') },
  { path: '/api/auth/forgot-password', loadModule: () => import('../src/pages/api/auth/forgot-password') },
  { path: '/api/auth/reset-password', loadModule: () => import('../src/pages/api/auth/reset-password') },
  { path: '/api/auth/revoke-all', loadModule: () => import('../src/pages/api/auth/revoke-all') },
  { path: '/api/semantic/search', loadModule: () => import('../src/pages/api/semantic/search') },
  { path: '/api/tokens/me', loadModule: () => import('../src/pages/api/tokens/me') },

  { path: '/api/resources', loadModule: () => import('../src/pages/api/resources/index') },
  { path: '/api/resources/public', loadModule: () => import('../src/pages/api/resources/public') },
  { path: '/api/resources/related', loadModule: () => import('../src/pages/api/resources/related') },
  { path: '/api/resources/starter-blocks', loadModule: () => import('../src/pages/api/resources/starter-blocks') },
  { path: '/api/resources/from-starter-block', loadModule: () => import('../src/pages/api/resources/from-starter-block') },
  { path: '/api/resources/generate', loadModule: () => import('../src/pages/api/resources/generate') },
  { path: '/api/resources/process', loadModule: () => import('../src/pages/api/resources/process') },
  { path: '/api/resources/upload', loadModule: () => import('../src/pages/api/resources/upload') },
  { path: '/api/resources/seed', loadModule: () => import('../src/pages/api/resources/seed') },
  { path: '/api/resources/deduplicate', loadModule: () => import('../src/pages/api/resources/deduplicate') },
  { path: '/api/resources/community-upload', loadModule: () => import('../src/pages/api/resources/community-upload') },
  { path: '/api/resources/:id', loadModule: () => import('../src/pages/api/resources/[id]') },
  { path: '/api/resources/:id/improve', loadModule: () => import('../src/pages/api/resources/[id]/improve') },

  { path: '/api/profiles', loadModule: () => import('../src/pages/api/profiles/index') },
  { path: '/api/profiles/default', loadModule: () => import('../src/pages/api/profiles/default') },
  { path: '/api/profiles/default/sync-corpus', loadModule: () => import('../src/pages/api/profiles/default/sync-corpus') },
  { path: '/api/profiles/create-base', loadModule: () => import('../src/pages/api/profiles/create-base') },
  { path: '/api/profiles/deduplicate', loadModule: () => import('../src/pages/api/profiles/deduplicate') },
  { path: '/api/profiles/:id', loadModule: () => import('../src/pages/api/profiles/[id]') },

  { path: '/api/community/by-topic', loadModule: () => import('../src/pages/api/community/by-topic') },
  { path: '/api/community/contributions', loadModule: () => import('../src/pages/api/community/contributions') },
  { path: '/api/community/my-contributions', loadModule: () => import('../src/pages/api/community/my-contributions') },
  { path: '/api/community/approve', loadModule: () => import('../src/pages/api/community/approve') },
  { path: '/api/community/reject', loadModule: () => import('../src/pages/api/community/reject') },

  { path: '/api/analytics/suggestions', loadModule: () => import('../src/pages/api/analytics/suggestions') },
  { path: '/api/admin/users', loadModule: () => import('../src/pages/api/admin/users') },
  { path: '/api/admin/auth-audit', loadModule: () => import('../src/pages/api/admin/auth-audit') },
  { path: '/api/admin/pipeline-config', loadModule: () => import('../src/pages/api/admin/pipeline-config') },
  { path: '/api/admin/reindex-resource', loadModule: () => import('../src/pages/api/admin/reindex-resource') },
  { path: '/api/admin/vectors-summary', loadModule: () => import('../src/pages/api/admin/vectors-summary') },
  { path: '/api/cron/provision-admin', loadModule: () => import('../src/pages/api/cron/provision-admin') },
];
