import type { RouteDefinition } from './astro-adapter';

export const standaloneApiRoutes: RouteDefinition[] = [
  { path: '/api/health', loadModule: () => import('../src/pages/_api/health') },
  { path: '/api/contact/inquiry', loadModule: () => import('../src/pages/_api/contact/inquiry') },
  { path: '/api/test', loadModule: () => import('../src/pages/_api/test') },
  { path: '/api/auth/login', loadModule: () => import('../src/pages/_api/auth/login') },
  { path: '/api/auth/logout', loadModule: () => import('../src/pages/_api/auth/logout') },
  { path: '/api/auth/me', loadModule: () => import('../src/pages/_api/auth/me') },
  { path: '/api/auth/register', loadModule: () => import('../src/pages/_api/auth/register') },
  { path: '/api/auth/verify-email', loadModule: () => import('../src/pages/_api/auth/verify-email') },
  { path: '/api/auth/resend-verification', loadModule: () => import('../src/pages/_api/auth/resend-verification') },
  { path: '/api/auth/forgot-password', loadModule: () => import('../src/pages/_api/auth/forgot-password') },
  { path: '/api/auth/reset-password', loadModule: () => import('../src/pages/_api/auth/reset-password') },
  { path: '/api/auth/revoke-all', loadModule: () => import('../src/pages/_api/auth/revoke-all') },
  { path: '/api/semantic/search', loadModule: () => import('../src/pages/_api/semantic/search') },
  { path: '/api/tokens/me', loadModule: () => import('../src/pages/_api/tokens/me') },
  { path: '/api/tokens/perks', loadModule: () => import('../src/pages/_api/tokens/perks') },
  { path: '/api/tokens/redeem', loadModule: () => import('../src/pages/_api/tokens/redeem') },
  { path: '/api/usage/me', loadModule: () => import('../src/pages/_api/usage/me') },
  { path: '/api/voice/analyze', loadModule: () => import('../src/pages/_api/voice/analyze') },
  { path: '/api/voice-map/corpus', loadModule: () => import('../src/pages/_api/voice-map/corpus') },
  { path: '/api/voice-map/principles', loadModule: () => import('../src/pages/_api/voice-map/principles') },
  { path: '/api/voice-map/semantic', loadModule: () => import('../src/pages/_api/voice-map/semantic') },

  { path: '/api/resources', loadModule: () => import('../src/pages/_api/resources/index') },
  { path: '/api/resources/public', loadModule: () => import('../src/pages/_api/resources/public') },
  { path: '/api/resources/related', loadModule: () => import('../src/pages/_api/resources/related') },
  { path: '/api/resources/search', loadModule: () => import('../src/pages/_api/resources/search') },
  { path: '/api/resources/starter-blocks', loadModule: () => import('../src/pages/_api/resources/starter-blocks') },
  { path: '/api/resources/from-starter-block', loadModule: () => import('../src/pages/_api/resources/from-starter-block') },
  { path: '/api/resources/generate', loadModule: () => import('../src/pages/_api/resources/generate') },
  { path: '/api/resources/process', loadModule: () => import('../src/pages/_api/resources/process') },
  { path: '/api/resources/upload', loadModule: () => import('../src/pages/_api/resources/upload') },
  { path: '/api/resources/seed', loadModule: () => import('../src/pages/_api/resources/seed') },
  { path: '/api/resources/deduplicate', loadModule: () => import('../src/pages/_api/resources/deduplicate') },
  { path: '/api/resources/community-upload', loadModule: () => import('../src/pages/_api/resources/community-upload') },
  { path: '/api/resources/:id', loadModule: () => import('../src/pages/_api/resources/[id]') },
  { path: '/api/resources/:id/improve', loadModule: () => import('../src/pages/_api/resources/[id]/improve') },

  { path: '/api/profiles', loadModule: () => import('../src/pages/_api/profiles/index') },
  { path: '/api/profiles/default', loadModule: () => import('../src/pages/_api/profiles/default') },
  { path: '/api/profiles/default/sync-corpus', loadModule: () => import('../src/pages/_api/profiles/default/sync-corpus') },
  { path: '/api/profiles/create-base', loadModule: () => import('../src/pages/_api/profiles/create-base') },
  { path: '/api/profiles/deduplicate', loadModule: () => import('../src/pages/_api/profiles/deduplicate') },
  { path: '/api/profiles/:id', loadModule: () => import('../src/pages/_api/profiles/[id]') },

  { path: '/api/community/by-topic', loadModule: () => import('../src/pages/_api/community/by-topic') },
  { path: '/api/community/contributions', loadModule: () => import('../src/pages/_api/community/contributions') },
  { path: '/api/community/my-contributions', loadModule: () => import('../src/pages/_api/community/my-contributions') },
  { path: '/api/community/approve', loadModule: () => import('../src/pages/_api/community/approve') },
  { path: '/api/community/reject', loadModule: () => import('../src/pages/_api/community/reject') },

  { path: '/api/analytics/suggestions', loadModule: () => import('../src/pages/_api/analytics/suggestions') },
  { path: '/api/admin/users', loadModule: () => import('../src/pages/_api/admin/users') },
  { path: '/api/admin/users/:id', loadModule: () => import('../src/pages/_api/admin/users/[id]') },
  { path: '/api/admin/auth-audit', loadModule: () => import('../src/pages/_api/admin/auth-audit') },
  { path: '/api/admin/pipeline-config', loadModule: () => import('../src/pages/_api/admin/pipeline-config') },
  { path: '/api/admin/reindex-resource', loadModule: () => import('../src/pages/_api/admin/reindex-resource') },
  { path: '/api/admin/vectors-summary', loadModule: () => import('../src/pages/_api/admin/vectors-summary') },
  { path: '/api/admin/search-corpus', loadModule: () => import('../src/pages/_api/admin/search-corpus') },
  { path: '/api/cron/provision-admin', loadModule: () => import('../src/pages/_api/cron/provision-admin') },
  { path: '/api/cron/library-growth', loadModule: () => import('../src/pages/_api/cron/library-growth') },

  { path: '/api/auth/passkey/login-options', loadModule: () => import('../src/pages/_api/auth/passkey/login-options') },
  { path: '/api/auth/passkey/login-verify', loadModule: () => import('../src/pages/_api/auth/passkey/login-verify') },
  { path: '/api/auth/passkey/register-options', loadModule: () => import('../src/pages/_api/auth/passkey/register-options') },
  { path: '/api/auth/passkey/register-verify', loadModule: () => import('../src/pages/_api/auth/passkey/register-verify') },
  { path: '/api/auth/passkey/credentials', loadModule: () => import('../src/pages/_api/auth/passkey/credentials') },

  { path: '/api/auth/oauth/status', loadModule: () => import('../src/pages/_api/auth/oauth/status') },
  { path: '/api/auth/oauth/google/start', loadModule: () => import('../src/pages/_api/auth/oauth/google/start') },
  { path: '/api/auth/oauth/google/callback', loadModule: () => import('../src/pages/_api/auth/oauth/google/callback') },

  { path: '/api/admin/library-growth', loadModule: () => import('../src/pages/_api/admin/library-growth') },
  { path: '/api/admin/growth-proposals', loadModule: () => import('../src/pages/_api/admin/growth-proposals') },
  { path: '/api/admin/site-sections', loadModule: () => import('../src/pages/_api/admin/site-sections') },
  { path: '/api/admin/hosting-status', loadModule: () => import('../src/pages/_api/admin/hosting-status') },
  { path: '/api/admin/email-hosting-checklist', loadModule: () => import('../src/pages/_api/admin/email-hosting-checklist') },
  { path: '/api/admin/bootstrap-voice-corpus', loadModule: () => import('../src/pages/_api/admin/bootstrap-voice-corpus') },
  { path: '/api/admin/token-redemptions', loadModule: () => import('../src/pages/_api/admin/token-redemptions') },
  { path: '/api/admin/token-redemptions/fulfill', loadModule: () => import('../src/pages/_api/admin/token-redemptions/fulfill') },
];
